[package]
name = "docsearch"
version = "0.1.0"
authors = ["Oleksandr Zinkevych <zso040399@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tantivy = "0.14.0"
walkdir = "2.3.1"
thiserror = "1.0.24"